import {FormField} from "@core/types/form-builder.model";
import {Validators} from "@angular/forms";
import {ComponentTypeEnum} from "@core/enums/component-type.enum";

export const bankCardInformationFormFields: FormField[] = [
  {
    key: 'bank',
    label: 'BANK',
    componentType: ComponentTypeEnum.DROPDOWN,
    validators: [Validators.required],
    placeholder: 'SELECT',
    maxLength: 500,
  },
  {
    key: 'accountName',
    label: 'ACCOUNT_NAME',
    componentType: ComponentTypeEnum.TEXTBOX,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'ENTER',
    maxLength: 500,
  },
  {
    key: 'swiftCode',
    label: 'SWIFT_CODE',
    componentType: ComponentTypeEnum.TEXTBOX,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'ENTER',
    maxLength: 500,
    hintMenu: true,
    hintHeading: 'WHAT_IS_SWIFT_CODE',
    hintDescription: 'SWIFT_CODE_DESCRIPTION',
  },
  {
    key: 'accountNumber',
    label: 'ACCOUNT_NUMBER',
    componentType: ComponentTypeEnum.TEXTBOX,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'ENTER',
    hintMenu: true,
    hintHeading: 'ACCOUNT_NUMBER',
    hintDescription: 'ACCOUNT_NUMBER_DESCRIPTION',
  },
  {
    key: 'sortCode',
    label: 'SORT_CODE',
    componentType: ComponentTypeEnum.TEXTBOX,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'ENTER',
    hintMenu: true,
    hintHeading: 'WHAT_IS_SORT_CODE',
    hintDescription: 'SORT_CODE_DESCRIPTION',
  },
  {
    key: 'iban',
    label: 'IBAN',
    componentType: ComponentTypeEnum.TEXTBOX,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'ENTER',
    hintMenu: true,
    hintHeading: 'WHAT_IS_IBAN',
    hintDescription: 'IBAN_DESCRIPTION',
  },
];

export const taxationSettingsFormFields: FormField[] = [
  {
    key: 'paymentMethod',
    label: 'PAYMENT_METHOD',
    componentType: ComponentTypeEnum.DROPDOWN,
    validators: [Validators.required],
    placeholder: 'SELECT',
    maxLength: 500,
  },
  {
    key: 'taxation',
    label: 'APPLY_DOUBLE_TAXATION_TO_COUNTRY',
    additionalTitle: 'Apply Double Taxation',
    checkbox: true,
    componentType: ComponentTypeEnum.DROPDOWN,
    validators: [Validators.required],
    placeholder: 'SELECT',
    hintMenu: true,
    hintHeading: 'DOUBLE_TAXATION_CODE',
    hintDescription: 'DOUBLE_TAXATION_DESCRIPTION',
  },
];

export const rsaFormFields: FormField[] = [
  {
    key: 'rsa',
    label: 'RSA_NUMBER',
    componentType: ComponentTypeEnum.TEXTBOX,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'ENTER',
    hintMenu: true,
    hintHeading: 'RSA',
    hintDescription: 'RSA_DESCRIPTION',
  },
  {
    key: 'date',
    label: 'PENSION_START_DATE',
    componentType: ComponentTypeEnum.DATEPICKER,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'SELECT_DATE',
    maxLength: 500,
  },
  {
    key: 'taxation',
    label: 'PENSION_FUND_ADMINISTRATOR',
    componentType: ComponentTypeEnum.DROPDOWN,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'SELECT',
    maxLength: 500,
  },
  {
    key: 'taxation',
    label: 'VOLUNTARY_CONTRIBUTION',
    componentType: ComponentTypeEnum.TEXTBOX,
    inputType: 'text',
    validators: [Validators.required],
    placeholder: 'ENTER',
    maxLength: 500,
  },
];
